### ISSUE TITLE
Sign in register

### ISSUE THREAD

**Issue by olymk2** [maidstone-hackspace/maidstone-hackspace-website#145]
Simple form to log visitors.

just first name, surname and date, this can also act as a fire register and just to see how many visitors we get over time.

**Comment by octamois** [comment]
@olymk2 Do you want that data to be stored in backend somewhere so where?

**Comment by olymk2** [comment]
yeah so a new model, with name and date. 

A new model form to enter the details.

Expose the model to the admin  area, and perhaps add a filter which default to today but let you view older dates

Don't need to link this in the nav really as its for people who physically come to the space.

anything else that could be useful to see who's visiting or data that may be needed.

want it minimal so people are not put of from filling it in.
