### ISSUE TITLE
Allow formatting in the blog and maybe other places

### ISSUE THREAD

**Issue by olymk2** [maidstone-hackspace/maidstone-hackspace-website#42]
Perhaps look at implementing this

https://github.com/sv0/django-markdown-app

or similar

**Comment by MightySCollins** [comment]
I was looking at https://github.com/aljosa/django-tinymce. It does not seem to have markdown support but does have HTML (https://www.tinymce.com/). Not sure which is better I kinda would like to use the HTML one and the flatpages plugin to allow all the static pages like about to be editable in the admin.

The only thing is do we want to allow people to write html?

**Comment by olymk2** [comment]
closing as we decide and implemented this :)
