### ISSUE TITLE
Allow users to add there rss feed

### ISSUE THREAD

**Issue by olymk2** [maidstone-hackspace/maidstone-hackspace-website#54]
allow user to add edit and disable there own feed

**Comment by MightySCollins** [comment]
Is it worth needing it approved?

**Comment by olymk2** [comment]
possibly in the future but perhaps not immediately we can have a think about it

**Comment by MightySCollins** [comment]
So my simple solution to approval was to make enabled uneditable and set to false. Then someone can manually enable it from the admin area

**Comment by olymk2** [comment]
not a bad shout, would need a small message to say why it was greyed out
