### ISSUE TITLE
RFID auth via an api

### ISSUE THREAD

**Issue by olymk2** [maidstone-hackspace/maidstone-hackspace-website#83]
Started to think about this one.

https://github.com/maidstone-hackspace/maidstone-hackspace-website/tree/rfid

**Comment by MightySCollins** [comment]
Looks good, does it need that mapping table etc as I thought Django could do something similar with a many to many relationships. So you could have RfidCards and RfidReciver(device) both with a many to many to the User https://docs.djangoproject.com/en/1.10/topics/db/examples/many_to_many/

**Comment by olymk2** [comment]
yeah i think your right that could work, we can think about it on wednesday

**Comment by olymk2** [comment]
um in retro spec, we probably do need a mapping table, the device table is the actual devices and we would have many users to it.

if we dont have the third table wee will be duplicating the device data like name so i think it will be needed.

Device
  - id
  - name
  - description

rfid cards
  - id
  - rfid_number
  - user

rfid_dedvice_auth
  - device_id
  - user_id

so when you auth a card it will send the id of the card and the device, it goes to the api looks up in the database against the mapping table and then looks up the device and user from there.

**Comment by olymk2** [comment]
by the way updated rest_framework locally, I did not get the updated doc view with the code examples. do i have to change something ?

**Comment by MightySCollins** [comment]
Nope not following, I will try and test something tomorrow without a
mapping table. Also you need to install the /doc route I think.

Sam Collins
theatrepro11@gmail.com
+44 7393 209 147

I PGP sign my E-Mails, you can find me at https://keybase.io/scollins. Feel
free to sign my key and send it back or send me an encrypted E-Mail.

**Comment by olymk2** [comment]
cool got the docs need to install coreapi and add in the urls as you said

**Comment by olymk2** [comment]
just pushed my latest code, if anyone want to try expand or what ever.

you will need to rebuild your containers, just starting to look at web tokens but of doing other stuff now.

**Comment by MightySCollins** [comment]
This might help: https://pythonhosted.org/django-otp/
