### ISSUE TITLE
Local events with dates, perhaps local resources

### ISSUE THREAD

**Issue by olymk2** [maidstone-hackspace/maidstone-hackspace-website#84]
be nice to have some where to put links and upcoming events like 
http://brightondigitalfestival.co.uk/
and emfcamp 2018, good to advertise them and show people what we like to get involved in.

Should be quite a simple one to implement, a few fields in a models and a simple view.

Index on where to source resources could be good as well, though this may be better done separately ?

**Comment by sgtwilko** [comment]
As mentioned on #186 -> https://github.com/dakrauth/django-swingtime
