### ISSUE TITLE
improve the backend ?

### ISSUE THREAD

**Issue by olymk2** [maidstone-hackspace/maidstone-hackspace-website#91]
We could apply this theme which @MightySCollins found which should give us a nicer backend some one want to try and test ? http://v2.djangosuit.com/admin/login/?next=/admin/

**Comment by MightySCollins** [comment]
Just something to note that's not quite released yet... Might need a bit of testing https://github.com/darklow/django-suit/tree/v2

**Comment by arshsherdill** [comment]
What exactly is to be done? Newbie here

**Comment by olymk2** [comment]
hi @arshsherdill we are thinking of changing the backend to use django suits currently it uses the default, if you fancy trying and testing go for it.

I would imagine its quite simple wee have not modified the backend much so you can probably follow the guide on the django suites site and put in a PR.
